// src-tauri/src/core/mod.rs
pub mod agents;
pub mod app_config;
pub mod audit;
pub mod discovery;
pub mod git;
pub mod github_api;
pub mod installer;
pub mod paths;
pub mod skill;
pub mod local_lock;
pub mod plugin_manifest;
pub mod skill_lock;
pub mod source_policy;
pub mod source_parser;
pub mod update_metadata;
pub mod update_source;
pub mod uninstaller;
pub mod wellknown;

pub use discovery::*;
pub use git::*;
pub use github_api::*;
pub use installer::*;
pub use app_config::*;
pub use source_policy::*;
pub use source_parser::*;
pub use update_metadata::*;
pub use update_source::*;
