#[cfg(debug_assertions)]
use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};

mod commands;
mod core;
mod error;
mod models;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // 创建 specta builder
    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::agents::list_agents,
            commands::skills::list_skills,
            commands::skills::read_skill_content,
            commands::config::get_config,
            commands::config::save_config,
            commands::config::get_last_selected_agents,
            commands::config::get_default_target_agents,
            commands::config::save_default_target_agents,
            commands::config::add_project,
            commands::config::remove_project,
            commands::config::check_project_path,
            commands::config::open_in_explorer,
            commands::install::fetch_available,
            commands::install::install_skills,
            commands::overwrites::check_overwrites,
            commands::remove::remove_skill,
            commands::remove_details::get_skill_agent_details,
            commands::duplicate_copies::cleanup_duplicate_agent_copy,
            commands::duplicate_copies::cleanup_duplicate_agent_copies,
            commands::update::check_updates,
            commands::update::update_skill,
            commands::update::update_skills_batch,
            commands::wizard::open_install_wizard,
            commands::audit::check_skill_audit,
            commands::manage_agents::manage_skill_agents,
            commands::copy_skill::copy_skill_to_projects,
            commands::copy_skill::check_skill_in_projects,
        ])
        .events(collect_events![]);

    // Debug 模式下导出 TypeScript 绑定
    #[cfg(debug_assertions)]
    builder
        .export(
            Typescript::default()
                .formatter(specta_typescript::formatter::prettier)
                .header("// 此文件由 tauri-specta 自动生成，请勿手动修改\n// This file is auto-generated by tauri-specta. Do not edit manually."),
            "../src/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.unminimize();
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            #[cfg(debug_assertions)]
            app.handle().plugin(
                tauri_plugin_log::Builder::default()
                    .level(log::LevelFilter::Info)
                    .build(),
            )?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
