// 此文件由 tauri-specta 自动生成，请勿手动修改
// This file is auto-generated by tauri-specta. Do not edit manually.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listAgents(context: ContextRef) : Promise<Result<AgentInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出指定项目内 Eve 可安装的具体目标：root agent 与已存在 subagents。
 */
async listEveInstallTargets(context: ContextRef) : Promise<Result<InstallTargetInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_eve_install_targets", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills(context: ContextRef) : Promise<Result<ListSkillsResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the markdown body of a skill's SKILL.md
 */
async readSkillContent(context: ContextRef, canonicalPath: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_skill_content", { context, canonicalPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取配置
 * 文件不存在或解析失败时返回默认配置
 */
async getConfig() : Promise<Result<SkillDeckConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 保存配置
 * 目录不存在时自动创建
 */
async saveConfig(config: SkillDeckConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultTargetAgents(context: ContextRef) : Promise<Result<DefaultTargetAgents | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_target_agents", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDefaultTargetAgents(context: ContextRef, defaults: DefaultTargetAgents) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_default_target_agents", { context, defaults }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中打开路径
 */
async openInExplorer(path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAvailable(context: ContextRef, source: string) : Promise<Result<FetchResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_available", { context, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installSkills(context: ContextRef, params: InstallParams) : Promise<Result<InstallResults, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_skills", { context, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeLifecycleAction(action: LifecycleAction) : Promise<Result<LifecycleActionOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_lifecycle_action", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检测哪些 skill × agent 组合会被覆盖
 *
 * # Arguments
 * * `skills` - 要安装的 skill 名称列表
 * * `agents` - 目标 agent 列表
 * * `scope` - 安装范围
 * * `project_path` - Project scope 时的项目路径
 *
 * # Returns
 * * `HashMap<String, Vec<String>>` - { skill_name: [agent_ids that will be overwritten] }
 */
async checkOverwrites(context: ContextRef, skills: string[], agents: string[], privateCopyAgents: string[], agentTargets: InstallTargetSpec[]) : Promise<Result<Partial<{ [key in string]: string[] }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_overwrites", { context, skills, agents, privateCopyAgents, agentTargets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除指定 skill
 *
 * # Arguments
 * * `scope` - 删除范围（global/project）
 * * `name` - skill 名称
 * * `project_path` - Project scope 时的项目路径
 * * `agents` - 部分移除时指定的 agent 列表（None 或空 = 完全删除）
 * * `full_removal` - 是否完全删除（true = 删除一切，false = 仅删除指定 agents 的 symlink）
 * * `agent_targets` - 具体目标列表；目前用于 Eve root/subagent 删除
 */
async removeSkill(context: ContextRef, name: string, agents: AgentType[] | null, fullRemoval: boolean | null, agentTargets: InstallTargetSpec[] | null) : Promise<Result<RemoveResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_skill", { context, name, agents, fullRemoval, agentTargets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSkillAgentDetails(context: ContextRef, name: string) : Promise<Result<SkillAgentDetails, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill_agent_details", { context, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupDuplicateAgentCopy(context: ContextRef, skillName: string, agent: AgentType) : Promise<Result<DuplicateCleanupResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_duplicate_agent_copy", { context, skillName, agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupDuplicateAgentCopies(context: ContextRef, skillName: string, agents: AgentType[]) : Promise<Result<DuplicateCleanupResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_duplicate_agent_copies", { context, skillName, agents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检测指定 scope 的 skills 是否有更新
 *
 * 流程：
 * 1. 读取对应 scope 的 lock 文件
 * 2. 从 lock entry 派生更新能力；不可检查的 entry 直接返回 cannot-check
 * 3. 对可检查的来源按 source/ref 分组，目前 GitHub 走 Trees API
 * 4. 比对记录的版本 hash 与远端 hash
 */
async checkUpdates(context: ContextRef) : Promise<Result<SkillUpdateInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_updates", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新指定 skill
 *
 * 本质是"重新安装"：从 lock 文件读取来源信息，构造安装 URL，复用安装逻辑。
 * 与 CLI update 命令行为一致。
 */
async updateSkill(context: ContextRef, name: string) : Promise<Result<UpdateSkillResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_skill", { context, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量更新多个 skills（同源 clone 合并）
 *
 * 按 source 分组，每组只 clone 一次仓库，然后从同一 clone 中安装所有该组的 skills。
 * 对于 N 个同源 skills，从 clone N 次降为 clone 1 次。
 */
async updateSkillsBatch(context: ContextRef, names: string[]) : Promise<Result<UpdateSkillResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_skills_batch", { context, names }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 打开安装向导独立窗口
 *
 * 必须为 async —— 同步 command 在主线程执行，
 * 而 WebviewWindowBuilder::build() 也需要主线程，会导致死锁。
 * async command 在异步线程执行，build() 可以安全回调主线程。
 */
async openInstallWizard(entryPoint: string, context: ContextRef, projectPath: string | null, prefillSource: string | null, prefillSkillName: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_install_wizard", { entryPoint, context, projectPath, prefillSource, prefillSkillName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检查 skill 的安全审计数据
 */
async checkSkillAudit(source: string, skills: string[]) : Promise<Result<Partial<{ [key in string]: SkillAuditData }> | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_skill_audit", { source, skills }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async manageSkillAgents(context: ContextRef, skillName: string, addAgents: AgentType[], removeAgents: AgentType[], privateCopyAgents: AgentType[], mode: InstallMode) : Promise<Result<ManageAgentsResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manage_skill_agents", { context, skillName, addAgents, removeAgents, privateCopyAgents, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copySkillToProjects(skillName: string, source: ContextRef, targets: ContextRef[], agents: string[], privateCopyAgents: string[]) : Promise<Result<CopySkillResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_skill_to_projects", { skillName, source, targets, agents, privateCopyAgents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEnvironments() : Promise<Result<EnvironmentDiscoverySnapshot, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_environments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectEnvironment(distroName: string) : Promise<Result<WslSession, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_environment", { distroName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mapEnvironmentPath(environment: EnvironmentRef, path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("map_environment_path", { environment, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEnvironmentProjects(environment: EnvironmentRef) : Promise<Result<ProjectInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_environment_projects", { environment }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addEnvironmentProject(environment: EnvironmentRef, nativePath: string) : Promise<Result<AddProjectResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_environment_project", { environment, nativePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeEnvironmentProject(environment: EnvironmentRef, projectId: string) : Promise<Result<ProjectInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_environment_project", { environment, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEnvironmentProjectCrossStorageWarning(environment: EnvironmentRef, projectId: string, suppressed: boolean) : Promise<Result<ProjectInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_environment_project_cross_storage_warning", { environment, projectId, suppressed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHostProjectMigration() : Promise<Result<ProjectInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_host_project_migration") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveMutation() : Promise<MutationSnapshot> {
    return await TAURI_INVOKE("get_active_mutation");
},
async requestCancelActiveMutation() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_cancel_active_mutation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
environmentRuntimeEvent: EnvironmentRuntimeEvent,
lifecycleActionRequestedEvent: LifecycleActionRequestedEvent
}>({
environmentRuntimeEvent: "environment-runtime-event",
lifecycleActionRequestedEvent: "lifecycle-action-requested-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActiveMutation = { id: string; kind: MutationKind; context: ContextRef; phase: MutationPhase; progress: MutationProgress | null; cancelable: boolean }
export type AddProjectResult = { project: ProjectInfo; created: boolean }
export type AgentAvailabilityKind = "shared-only" | "shared-compatible" | "private-required" | "unknown" | "unsupported"
/**
 * Agent 信息（返回给前端）
 * 对应 CLI: 综合 AgentConfig + detectInstalled 结果
 */
export type AgentInfo = { id: AgentType; name: string; skillsDir: string; globalSkillsDir: string; detected: boolean;
/**
 * 按安装范围计算后的目标能力
 */
targets: AgentTargets }
/**
 * Agent 对某个 skill 的 presence 摘要
 */
export type AgentPresenceInfo = { agent: AgentType; displayName: string; presence: AgentSkillPresence; sharedPath: string; privatePath: string | null; canCleanupPrivateCopy: boolean }
/**
 * Agent 在单个安装范围下的目标能力
 */
export type AgentScopeTarget = { supported: boolean; automatic: boolean; path: string; availability: AgentAvailabilityKind; defaultAvailable: boolean; sharedPath: string; installPath: string; readPaths: string[]; privatePath: string | null }
/**
 * Agent 对某个 skill 的安装/可用状态
 */
export type AgentSkillPresence = "default-active" | "requires-private-install" | "duplicate-copy" | "private-only" | "not-installed"
/**
 * Agent 在全局和项目两个安装范围下的目标能力
 */
export type AgentTargets = { global: AgentScopeTarget; project: AgentScopeTarget }
/**
 * Agent 类型枚举
 * 完整对应 CLI: types.ts AgentType
 */
export type AgentType = "aider-desk" | "amp" | "antigravity" | "antigravity-cli" | "astrbot" | "augment" | "autohand-code" | "bob" | "claude-code" | "openclaw" | "cline" | "codearts-agent" | "codebuddy" | "codemaker" | "codestudio" | "codex" | "command-code" | "continue" | "crush" | "cursor" | "deepagents" | "devin" | "dexto" | "droid" | "eve" | "firebender" | "forgecode" | "gemini-cli" | "github-copilot" | "goose" | "hermes-agent" | "iflow-cli" | "junie" | "kilo" | "kimi-code-cli" | "kiro-cli" | "kode" | "inference-sh" | "jazz" | "lingma" | "loaf" | "mcpjam" | "mistral-vibe" | "moxby" | "mux" | "neovate" | "ona" | "opencode" | "openhands" | "pi" | "promptscript" | "qoder" | "qoder-cn" | "qwen-code" | "reasonix" | "replit" | "rovodev" | "roo" | "tabnine-cli" | "trae" | "trae-cn" | "warp" | "windsurf" | "zed" | "zencoder" | "zenflow" | "pochi" | "adal" | "cortex" | "terramind" | "tinycloud"
export type AppError = { kind: "io"; data: { message: string } } | { kind: "yaml"; data: { message: string } } | { kind: "json"; data: { message: string } } | { kind: "invalidSkillMd"; data: { message: string } } | { kind: "path"; data: { message: string } } | { kind: "invalidSource"; data: { value: string } } | { kind: "gitCloneFailed"; data: { message: string } } | { kind: "gitAuthFailed"; data: { message: string } } | { kind: "gitRepoNotFound"; data: { repo: string } } | { kind: "gitRefNotFound"; data: { refName: string } } | { kind: "gitTimeout"; data: { timeoutSecs: number } } | { kind: "gitNetworkError"; data: { message: string } } |
/**
 * GitHub API 调用失败,带机器可读的 reason 让前端可以区分文案。
 * reason 当前取值: `rate-limited` / `network-error` / `auth` / `http-<code>`。
 */
{ kind: "gitHubApiError"; data: { reason: string; message: string } } | { kind: "pathNotFound"; data: { path: string } } | { kind: "installFailed"; data: { message: string } } | { kind: "installRiskConfirmationRequired"; data: { code: string } } | { kind: "noSkillsFound" } | { kind: "mutationBusy" } | { kind: "applicationTerminating" } | { kind: "mutationCancelled" } | { kind: "environmentDiscoveryFailed"; data: { message: string } } | { kind: "wslCommandTimedOut" } | { kind: "wslOutputLimitExceeded"; data: { stream: string; limit: number } } | { kind: "wslCommandFailed"; data: { exitCode: number | null; stderr: string } } | { kind: "environmentUnavailable"; data: { environment: EnvironmentRef; message: string } } | { kind: "storageMappingUnsupported"; data: { path: string; environment: EnvironmentRef } } | { kind: "projectMigrationFailed"; data: { message: string } } | { kind: "lockConflict"; data: { target: LockConflictTarget } } | { kind: "invalidAgent"; data: { agent: string } } | { kind: "custom"; data: { message: string } }
/**
 * 可用的 Skill 信息（fetch_available 返回）
 */
export type AvailableSkill = {
/**
 * Skill 名称
 */
name: string;
/**
 * 安装时使用的目录名
 */
installDirName: string;
/**
 * 描述
 */
description: string;
/**
 * 仓库内相对路径
 */
relativePath: string;
/**
 * 所属 plugin 名称（来自 .claude-plugin/ manifest）
 */
pluginName?: string | null;
/**
 * Well-known discovery protocol version, if applicable.
 */
wellKnownVersion?: string | null;
/**
 * Well-known entry type: legacy, skill-md, or archive.
 */
wellKnownEntryType?: string | null;
/**
 * Hostname of the fetched artifact URL for v2 entries.
 */
artifactUrlHost?: string | null;
/**
 * Whether the v2 artifact digest was verified.
 */
digestVerified?: boolean | null;
/**
 * Compact trust reason for UI display.
 */
trustReason?: string | null }
export type ContextRef = { environment: EnvironmentRef; scope: ContextScope }
export type ContextScope = { scope: "global" } | { scope: "project"; project_id: string }
/**
 * 单个目标项目的复制结果
 */
export type CopyProjectResult = {
/**
 * 目标项目路径
 */
projectPath: string;
/**
 * 是否成功
 */
success: boolean;
/**
 * 错误信息
 */
error: string | null;
/**
 * 默认可用的 agents
 */
defaultAvailableAgents?: string[];
/**
 * 需要单独适配且写入成功的 agents
 */
privateAdaptedAgents?: string[];
/**
 * 明确写入独立副本的 agents
 */
privateCopyAgents?: string[];
/**
 * 因目标项目缺少 agent 根目录而跳过的 agents
 */
skippedAgents?: string[];
/**
 * 复制后目标项目的更新信息保留状态
 */
updateMetadataStatus: CopyUpdateMetadataStatus;
/**
 * 更新信息降级原因
 */
updateMetadataReason?: string | null }
/**
 * 复制结果汇总
 */
export type CopySkillResult = { results: CopyProjectResult[] }
/**
 * 复制后目标项目的更新信息保留状态
 */
export type CopyUpdateMetadataStatus = "preserved" | "incomplete" | "missing"
/**
 * GUI 使用的 scope-aware 默认安装目标
 */
export type DefaultTargetAgents = { global: string[]; project: string[] }
export type DuplicateCleanupResult = { agent: AgentType; success: boolean; skipped: boolean; path: string; error: string | null }
export type EnvironmentDiscoverySnapshot = { environments: EnvironmentInfo[]; error: AppError | null }
export type EnvironmentInfo = { environment: EnvironmentRef; displayName: string; status: EnvironmentStatus }
export type EnvironmentRef = { kind: "host" } | { kind: "wsl"; distro_name: string }
export type EnvironmentRuntimeEvent = { environment: EnvironmentRef; status: EnvironmentStatus; error: AppError | null }
export type EnvironmentStatus = "available" | "connecting" | "unavailable" | "error"
/**
 * fetch_available 返回结果
 */
export type FetchResult = {
/**
 * 来源类型
 */
sourceType: string;
/**
 * 规范化 URL
 */
sourceUrl: string;
/**
 * Git ref（branch/tag）
 */
gitRef?: string | null;
/**
 * @skill 语法提取的名称（用于预选）
 */
skillFilter: string | null;
/**
 * 安装前风险策略
 */
riskPolicy: InstallRiskPolicy;
/**
 * 可用的 skills 列表
 */
skills: AvailableSkill[] }
/**
 * 需要独立安装记录的 Agent 详情
 */
export type IndependentAgentInfo = {
/**
 * Agent 类型
 */
agent: AgentType;
/**
 * Agent 显示名称
 */
displayName: string;
/**
 * 安装路径
 */
path: string;
/**
 * 是否是 symlink（false 表示 copy 模式安装）
 */
isSymlink: boolean }
/**
 * 安装模式
 */
export type InstallMode = "symlink" | "copy"
/**
 * 安装参数
 */
export type InstallParams = {
/**
 * 原始来源字符串
 */
source: string;
/**
 * 选中的 skill 名称列表
 */
skills: string[];
/**
 * 目标 agents
 */
agents: string[];
/**
 * 具体安装目标。Eve root/subagent 和未来非 AgentType 目标使用该字段。
 */
agentTargets?: InstallTargetSpec[];
/**
 * 明确要求写入独立副本的 agents
 */
privateCopyAgents?: string[];
/**
 * 安装范围
 */
scope: Scope;
/**
 * Project scope 时的项目路径
 */
projectPath: string | null;
/**
 * 安装模式
 */
mode: InstallMode;
/**
 * 是否为重试模式（仅重试指定 skills + agents）
 */
retry?: boolean;
/**
 * 是否按每个已安装 Agent 的现有 copy/symlink 模式重新安装
 */
preserveExistingModes?: boolean;
/**
 * 是否已确认风险来源（如 OpenClaw）
 */
acknowledgeRisk?: boolean }
/**
 * 单个 skill 的安装结果
 */
export type InstallResult = {
/**
 * Skill 名称
 */
skillName: string;
/**
 * Agent 名称
 */
agent: string;
/**
 * 具体目标 ID，例如 `eve:root` 或 `eve:research`
 */
targetId?: string | null;
/**
 * Eve subagent 名称；Eve root 和非 Eve Agent 为空
 */
subagent?: string | null;
/**
 * 是否成功
 */
success: boolean;
/**
 * 安装路径
 */
path: string;
/**
 * Canonical 路径（symlink 模式）
 */
canonicalPath: string | null;
/**
 * 实际使用的安装模式
 */
mode: InstallMode;
/**
 * symlink 是否失败并降级为 copy
 */
symlinkFailed: boolean;
/**
 * project scope 中因目标 agent 根目录不存在而跳过
 */
skipped: boolean;
/**
 * 错误信息
 */
error: string | null;
/**
 * 安装结果分类
 */
category?: InstallResultCategory }
/**
 * 安装结果分类
 */
export type InstallResultCategory = "default-available" | "private-adapted" | "private-copy" | "skipped" | "failed"
/**
 * 安装结果汇总
 */
export type InstallResults = {
/**
 * 成功的安装
 */
successful: InstallResult[];
/**
 * 失败的安装
 */
failed: InstallResult[];
/**
 * symlink 失败降级为 copy 的 agents
 */
symlinkFallbackAgents: string[];
/**
 * 默认可用的 agents
 */
defaultAvailableAgents?: string[];
/**
 * 需要独立适配的 agents
 */
privateAdaptedAgents?: string[];
/**
 * 明确写入独立副本的 agents
 */
privateCopyAgents?: string[];
/**
 * 具体目标详情，主要用于 Eve root/subagent 展示
 */
targetDetails?: InstallTargetInfo[] }
/**
 * 风险策略种类
 */
export type InstallRiskKind = "none" | "require-confirmation"
/**
 * 安装风险策略
 */
export type InstallRiskPolicy = { kind: InstallRiskKind; code?: string | null }
/**
 * 具体安装目标展示信息，供前端确认页、完成页和目标选择使用。
 */
export type InstallTargetInfo = { targetId: string; agent: AgentType; displayName: string; subagent?: string | null; path: string }
/**
 * 具体安装目标请求。Eve root/subagent 使用该模型表达，不再只依赖 Agent 类型。
 */
export type InstallTargetSpec = { agent: AgentType; subagent?: string | null }
/**
 * 已安装的 Skill 信息
 * 对应 CLI: InstalledSkill (installer.ts:783-790)
 */
export type InstalledSkill = { name: string; description: string; path: string; canonicalPath: string; scope: SkillScope; agents: AgentType[];
/**
 * Skill card Agents that are both effective for this skill and detected locally.
 */
cardAgents?: AgentType[] | null; source?: string | null; sourceUrl?: string | null; installedAt?: string | null; updatedAt?: string | null; hasUpdate?: boolean | null;
/**
 * 是否可直接执行更新
 */
canRunUpdate?: boolean | null;
/**
 * 是否可自动检查更新
 */
canCheckForUpdates?: boolean | null;
/**
 * 更新能力缺失原因
 */
updateReason?: string | null;
/**
 * 所属 plugin 名称
 */
pluginName?: string | null;
/**
 * Git ref（branch/tag）
 */
gitRef?: string | null;
/**
 * 默认可用 Agent 数量
 */
defaultAvailableAgentCount?: number | null;
/**
 * 已独立适配 Agent 数量
 */
privateAdaptedAgentCount?: number | null;
/**
 * 可清理的额外 Agent 目录项数量（可能是链接或副本）
 */
duplicateCopyCount?: number | null;
/**
 * 默认可用 Agents
 */
defaultAvailableAgents?: AgentType[] | null;
/**
 * 需要/已有单独适配的 Agents
 */
privateAdaptedAgents?: AgentType[] | null;
/**
 * 当前存在额外 Agent 目录项的 Agents（可能是链接或副本）
 */
duplicateCopyAgents?: AgentType[] | null;
/**
 * 当前只通过 Agent 目录项使用的 Agents
 */
privateOnlyAgents?: AgentType[] | null;
/**
 * 需要额外保留到 Agent 目录的默认可用 Agents
 */
privateCopyAgents?: AgentType[] | null }
export type LifecycleAction = "closeCurrentWindow" | "quitApplication" | "restartApplication"
export type LifecycleActionOutcome = { status: "performed" } | { status: "delegated" } | { status: "blocked"; snapshot: MutationSnapshot }
export type LifecycleActionRequestedEvent = { action: LifecycleAction }
/**
 * list_skills 返回结果
 * 包含 skills 列表和路径存在性信息
 */
export type ListSkillsResult = { skills: InstalledSkill[];
/**
 * 项目目录是否存在（project scope 时有意义，global 始终为 true）
 */
pathExists: boolean }
export type LockConflictTarget = { kind: "skill"; skillName: string } | { kind: "rootField"; field: string }
/**
 * 单个 agent 添加操作结果
 */
export type ManageAgentOperationResult = { agent: string; success: boolean; mode: InstallMode; path: string; error: string | null }
/**
 * Agent 管理操作结果
 */
export type ManageAgentsResult = {
/**
 * 成功添加的 agent IDs
 */
added: string[];
/**
 * 每个新增 agent 的详细结果
 */
addedResults: ManageAgentOperationResult[];
/**
 * 成功移除的 agent IDs
 */
removed: string[];
/**
 * 错误信息列表
 */
errors: string[] }
export type MutationKind = "install" | "update" | "remove" | "copy" | "manageAgents" | "duplicateCleanup" | "repair" | "saveAgentDefaults" | "batchUpdate" | "projectMigration" | "addProject" | "removeProject" | "updateProjectPreference"
export type MutationPhase = "preparing" | "acquiring" | "materializing" | "committing" | "finishing"
export type MutationProgress = { subject: string | null; current: number | null; total: number | null }
export type MutationSnapshot = { revision: number; active: ActiveMutation | null }
export type ProjectBinding = { id: string; nativePath: string; displayName: string | null; order: number | null; suppressCrossStorageWarning?: boolean }
export type ProjectInfo = { binding: ProjectBinding; storage: ProjectStorageInfo }
export type ProjectStorageInfo = { access: StorageAccess; owner: EnvironmentRef | null }
/**
 * 单个 skill 的删除结果
 * 对应 CLI: remove.ts 第 148-195 行的 results 数组元素
 */
export type RemoveResult = {
/**
 * Skill 名称
 */
skillName: string;
/**
 * 是否成功
 */
success: boolean;
/**
 * 删除的 agent 目录路径列表
 */
removedPaths: string[];
/**
 * 来源信息（从 lock file 读取，仅 Global）
 */
source: string | null;
/**
 * 来源类型
 */
sourceType: string | null;
/**
 * 错误信息
 */
error: string | null }
/**
 * 风险等级
 */
export type RiskLevel = "safe" | "low" | "medium" | "high" | "critical" | "unknown"
/**
 * 安装范围
 */
export type Scope = "global" | "project"
/**
 * Skill 的 Agent 安装详情（用于智能删除对话框）
 */
export type SkillAgentDetails = {
/**
 * Skill 名称
 */
skillName: string;
/**
 * 安装范围
 */
scope: Scope;
/**
 * Canonical 目录路径
 */
canonicalPath: string;
/**
 * 自动读取 shared canonical 目录的 Agents（带显示名称）
 */
automaticAgents: ([AgentType, string])[];
/**
 * 有独立 symlink 或 copy 的 Agents
 */
independentAgents: IndependentAgentInfo[];
/**
 * 默认位置已生效的 Agents
 */
defaultAvailableAgents?: AgentPresenceInfo[];
/**
 * 需要单独适配但尚未安装私有目录的 Agents
 */
privateRequiredAgents?: AgentPresenceInfo[];
/**
 * 默认位置和私有目录都存在的重复副本 Agents
 */
duplicateCopyAgents?: AgentPresenceInfo[];
/**
 * 仅私有目录存在的 Agents
 */
privateOnlyAgents?: AgentPresenceInfo[];
/**
 * Eve root/subagent 具体目标。
 */
eveTargets?: InstallTargetInfo[] }
/**
 * Skill 审计数据
 */
export type SkillAuditData = { risk: RiskLevel; alerts?: number | null; score?: number | null; analyzedAt: string }
/**
 * Skill Deck 应用配置
 * 持久化到 ~/.skill-deck/config.json
 */
export type SkillDeckConfig = {
/**
 * 已保存的项目路径列表
 */
projects?: string[];
/**
 * Git 仓库拉取超时（秒）
 */
gitCloneTimeoutSecs?: number; hiddenWslDistros?: string[]; lastSelectedEnvironment?: EnvironmentRef | null; lastConnectedWslUserByDistro?: Partial<{ [key in string]: string }> }
/**
 * Skill 范围
 */
export type SkillScope = "global" | "project"
/**
 * 更新检测结果
 */
export type SkillUpdateCheckStatus = "update-available" | "up-to-date" | "cannot-check" | "deleted-upstream"
export type SkillUpdateInfo = { name: string; source: string; hasUpdate: boolean; status: SkillUpdateCheckStatus; reason?: string | null; gitRef?: string | null; sourceUrl?: string | null; skillPath?: string | null }
export type StorageAccess = "native" | "crossStorage" | "unsupported" | "unknown"
/**
 * agent 级更新结果
 */
export type UpdateSkillAgentResult = { agent: string; targetId?: string | null; subagent?: string | null; status: UpdateSkillAgentStatus; mode?: InstallMode | null; error?: string | null; durationMs?: number | null }
/**
 * 单个 agent 的更新状态
 */
export type UpdateSkillAgentStatus = "success" | "failed" | "skipped"
/**
 * skill 级更新结果
 */
export type UpdateSkillItemResult = { name: string; status: UpdateSkillStatus; error?: string | null; reason?: string | null; source?: string | null; sourceUrl?: string | null; gitRef?: string | null; skillPath?: string | null; warnings?: string[]; durationMs?: number | null; agentResults?: UpdateSkillAgentResult[] }
/**
 * 更新命令返回结果
 */
export type UpdateSkillResponse = { results: UpdateSkillItemResult[]; summary: UpdateSkillSummary }
/**
 * 单个 skill 的更新状态
 */
export type UpdateSkillStatus = "success" | "partial" | "failed" | "skipped"
/**
 * 更新汇总
 */
export type UpdateSkillSummary = { total: number; succeeded: number; partial: number; failed: number; skipped: number }
export type WslSession = { distroName: string; user: string; uid: number; home: string; xdgStateHome: string | null; configHome: string; environment: Partial<{ [key in string]: string }>; gitAvailable: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

export function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
